package dk.brics.tajs.analysis.dom;

import dk.brics.tajs.analysis.NativeAPIs;
import dk.brics.tajs.flowgraph.NativeObject;

/**
 * Native DOM objects.
 */
public enum DOMObjects implements NativeObject {

    // /////////////////////////////////////////////////////////////////////////
    // / WINDOW ///
    // /////////////////////////////////////////////////////////////////////////
    // DOM LEVEL 0: WINDOW HISTORY
    WINDOW_HISTORY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history"),
    WINDOW_HISTORY_BACK(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history.back"),
    WINDOW_HISTORY_FORWARD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history.forward"),
    WINDOW_HISTORY_GO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history.go"),

    // DOM LEVEL 0: WINDOW LOCATION
    WINDOW_LOCATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location"),
    WINDOW_LOCATION_ASSIGN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.assign"),
    WINDOW_LOCATION_RELOAD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.reload"),
    WINDOW_LOCATION_REPLACE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.replace"),
    WINDOW_LOCATION_TOSTRING(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.toString"),

    // DOM LEVEL 0: WINDOW NAVIGATOR
    WINDOW_NAVIGATOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Navigator"),

    // DOM LEVEL 0: WINDOW SCREEN
    WINDOW_SCREEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.screen"),

    // DOM LEVEL 0: WINDOW MISC
    WINDOW_ALERT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.alert"),
    WINDOW_ATOB(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.atob"),
    WINDOW_BACK(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.back"),
    WINDOW_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.blur"),
    WINDOW_BTOA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.btoa"),
    WINDOW_CLEAR_INTERVAL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.clearInterval"),
    WINDOW_CLEAR_TIMEOUT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.clearTimeout"),
    WINDOW_CLOSE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.close"),
    WINDOW_CONFIRM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.confirm"),
    WINDOW_ESCAPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.escape"),
    WINDOW_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.focus"),
    WINDOW_FORWARD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.forward"),
    WINDOW_HOME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.home"),
    WINDOW_MAXIMIZE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.maximize"),
    WINDOW_MINIMIZE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.minimize"),
    WINDOW_MOVEBY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.moveBy"),
    WINDOW_MOVETO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.moveTo"),
    WINDOW_OPEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.open"),
    WINDOW_PRINT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.print"),
    WINDOW_PROMPT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.prompt"),
    WINDOW_RESIZEBY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.resizeBy"),
    WINDOW_RESIZETO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.resizeTo"),
    WINDOW_SCROLL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scroll"),
    WINDOW_SCROLLBY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollBy"),
    WINDOW_SCROLLBYLINES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollByLines"),
    WINDOW_SCROLLBYPAGES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollByPages"),
    WINDOW_SCROLLTO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollTo"),
    WINDOW_SET_INTERVAL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.setInterval"),
    WINDOW_SET_TIMEOUT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.setTimeout"),
    WINDOW_STOP(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.stop"),
    WINDOW_UNESCAPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.unescape"),

    // DOM LEVEL 0: addEventListener / removeEventListener
    WINDOW_ADD_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.addEventListener"),
    WINDOW_REMOVE_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.removeEventListener"),

    // /////////////////////////////////////////////////////////////////////////
    // / DOCUMENT ///
    // /////////////////////////////////////////////////////////////////////////

    // DOM LEVEL 1
    DOCUMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document constructor"),
    DOCUMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.prototype"),
    DOCUMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document instances"),
    DOCUMENT_CREATEPROCESSINGINSTRUCTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createProcessingInstruction"),
    DOCUMENT_CREATE_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createAttribute"),
    DOCUMENT_CREATE_CDATASECTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createCDATASection"),
    DOCUMENT_CREATE_COMMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createComment"),
    DOCUMENT_CREATE_DOCUMENTFRAGMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createDocumentFragment"),
    DOCUMENT_CREATE_ELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createElement"),
    DOCUMENT_CREATE_ENTITYREFERENCE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createEntityReference"),
    DOCUMENT_CREATE_TEXTNODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createTextNode"),
    DOCUMENT_GET_ELEMENTS_BY_TAGNAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.getElementsByTagName"),

    // DOM LEVEL 2
    DOCUMENT_CREATE_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createAttributeNS"),
    DOCUMENT_CREATE_ELEMENT_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createElementNS"),
    DOCUMENT_GET_ELEMENTS_BY_TAGNAME_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.getElementsByTagNameNS"),
    DOCUMENT_GET_ELEMENT_BY_ID(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.getElementById"),
    DOCUMENT_IMPORT_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.importNode"),

    // DOM LEVEL 3
    DOCUMENT_RENAME_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.renameNode"),
    DOCUMENT_NORMALIZEDOCUMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.normalizeDocument"),
    DOCUMENT_ADOPT_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.adoptNode"),

    // /////////////////////////////////////////////////////////////////////////
    // / EVENT ///
    // /////////////////////////////////////////////////////////////////////////

    EVENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event constructor"),
    EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event.prototype"),
    EVENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event instances"),
    EVENT_STOP_PROPAGATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event.stopPropagation"),
    EVENT_PREVENT_DEFAULT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event.preventDefault"),
    EVENT_INIT_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event.initEvent"),
    EVENT_TARGET(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget"),
    EVENT_TARGET_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.prototype"),
    EVENT_TARGET_ADD_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.addEventListener"),
    EVENT_TARGET_REMOVE_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.removeEventListener"),
    EVENT_TARGET_DISPATCH_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.dispatchEvent"),
    EVENT_LISTENER_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventListener"),
    EVENT_LISTENER_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventListener.prototype"),
    EVENT_LISTENER_HANDLE_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventListener.handleEvent"),
    EVENT_EXCEPTION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventException constructor"),
    EVENT_EXCEPTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventException.prototype"),
    EVENT_EXCEPTION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventException instances"),
    DOCUMENT_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentEvent"),
    DOCUMENT_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentEvent.prototype"),
    DOCUMENT_EVENT_CREATE_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentEvent.createEvent"),
    UI_EVENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "UIEvent"),
    UI_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "UIEvent.prototype"),
    UI_EVENT_INIT_UI_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "UIEvent.initUIEvent"),
    MOUSE_EVENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MouseEvent"),
    MOUSE_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MouseEvent.prototype"),
    MOUSE_EVENT_INIT_MOUSE_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MouseEvent.initMouseEvent"),
    KEYBOARD_EVENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent"),
    KEYBOARD_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.prototype"),
    KEYBOARD_EVENT_GET_MODIFIER_STATE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.getModifierState"),
    KEYBOARD_EVENT_INIT_KEYBOARD_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.initKeyboardEvent"),
    KEYBOARD_EVENT_INIT_KEYBOARD_EVENT_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.initKeyboardEventNS"),
    MUTATION_EVENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MutationEvent"),
    MUTATION_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MutationEvent.prototype"),
    MUTATION_EVENT_INIT_MUTATION_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MutationEvent.initMutationEvent"),
    WHEEL_EVENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent"),
    WHEEL_EVENT_INIT_WHEEL_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent.initWheelEvent"),
    WHEEL_EVENT_INIT_WHEEL_EVENT_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent.initWheelEventNS"),
    WHEEL_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent.prototype"),

    // /////////////////////////////////////////////////////////////////////////
    // / VIEWS ///
    // /////////////////////////////////////////////////////////////////////////
    ABSTRACT_VIEW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "AbstractView"),

    // /////////////////////////////////////////////////////////////////////////
    // / DOM CORE ///
    // /////////////////////////////////////////////////////////////////////////
    ELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element constructor"),
    ELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.prototype"),
    ELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element instances"),
    ELEMENT_GET_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttribute"),
    ELEMENT_GET_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttributeNS"),
    ELEMENT_GET_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttributeNode"),
    ELEMENT_GET_ATTRIBUTE_NODE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttributeNodeNS"),
    ELEMENT_GET_BOUNDING_CLIENT_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getBoundingClientRect"),
    ELEMENT_GET_ELEMENTS_BY_TAGNAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getElementsByTagName"),
    ELEMENT_GET_ELEMENTS_BY_TAGNAME_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getElementsByTagNameNS"),
    ELEMENT_HAS_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.hasAttribute"),
    ELEMENT_HAS_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.hasAttributeNS"),
    ELEMENT_REMOVE_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.removeAttribute"),
    ELEMENT_REMOVE_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.removeAttributeNS"),
    ELEMENT_REMOVE_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.removeAttributeNode"),
    ELEMENT_SET_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttribute"),
    ELEMENT_SET_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttributeNS"),
    ELEMENT_SET_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttributeNode"),
    ELEMENT_SET_ATTRIBUTE_NODE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttributeNodeNS"),
    ELEMENT_SET_ID_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setIdAttributeNode"),
    ELEMENT_SET_ID_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setIdAttributeNodeNS"),
    ELEMENT_SET_ID_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setIdAttributeNodeNode"),

    ATTR_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Attr constructor"),
    ATTR_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Attr.prototype"),
    ATTR_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Attr instances"),
    CDATASECTION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CDATASection constructor"),
    CDATASECTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CDATASection.prototype"),
    CDATASECTION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CDATASection instances"),
    COMMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Comment constructor"),
    COMMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Comment.prototype"),
    COMMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Comment instances"),
    CHARACTERDATA_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData constructor"),
    CHARACTERDATA_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.prototype"),
    CHARACTERDATA_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData instances"),
    CHARACTERDATA_SUBSTRINGDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.substringData"),
    CHARACTERDATA_APPENDDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.appendData"),
    CHARACTERDATA_INSERTDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.insertData"),
    CHARACTERDATA_DELETEDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.deleteData"),
    CHARACTERDATA_REPLACEDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.replaceData"),
    DOCUMENTTYPE_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentType constructor"),
    DOCUMENTTYPE_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentType.prototype"),
    DOCUMENTTYPE_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentType instances"),
    DOCUMENTFRAGMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentFragment constructor"),
    DOCUMENTFRAGMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentFragment.prototype"),
    DOCUMENTFRAGMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentFragment instances"),
    ENTITY_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Entity constructor"),
    ENTITY_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Entity.prototype"),
    ENTITY_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Entity instances"),
    ENTITYREFERENCE_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EntityReference constructor"),
    ENTITYREFERENCE_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EntityReference.prototype"),
    ENTITYREFERENCE_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EntityReference instances"),

    NODE_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node constructor"),
    NODE_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.prototype"),
    NODE_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node instances"),
    NODE_APPEND_CHILD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.appendChild"),
    NODE_CLONE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.cloneNode"),
    NODE_INSERT_BEFORE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.insertBefore"),
    NODE_HAS_CHILD_NODES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.hasChildNodes"),
    NODE_REMOVE_CHILD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.removeChild"),
    NODE_REPLACE_CHILD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.replaceChild"),
    NODE_IS_SUPPORTED(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.isSupported"),
    NODE_HAS_ATTRIBUTES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.hasAttributes"),
    NODE_NORMALIZE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.normalize"),

    NODELIST_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NodeList constructor"),
    NODELIST_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NodeList.prototype"),
    NODELIST_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NodeList instances"),
    NODELIST_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NodeList.item"),

    PROCESSINGINSTRUCTION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ProcessingInstruction constructor"),
    PROCESSINGINSTRUCTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ProcessingInstruction.prototype"),
    PROCESSINGINSTRUCTION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ProcessingInstruction instances"),
    CONFIGURATION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration constructor"),
    CONFIGURATION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.prototype"),
    CONFIGURATION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration instances"),
    CONFIGURATION_GET_PARAMETER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.getParameter"),
    CONFIGURATION_SET_PARAMETER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.setParameter"),
    CONFIGURATION_CAN_SET_PARAMETER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.canSetParameter"),
    DOMEXCEPTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMException"),
    DOMEXCEPTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMException.prototype"),
    DOMIMPLEMENTATION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMImplementation constructor"),
    DOMIMPLEMENTATION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMImplementation.prototype"),
    DOMIMPLEMENTATION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMImplementation instances"),
    DOMIMPLEMENTATION_HASFEATURE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "hasFeature"),
    DOMIMPLEMENTATION_CREATEDOCUMENTTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "createDocumentType"),
    DOMIMPLEMENTATION_CREATEDOCUMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "createDocument"),
    NAMEDNODEMAP_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap constructor"),
    NAMEDNODEMAP_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.prototype"),
    NAMEDNODEMAP_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap instances"),
    NAMEDNODEMAP_PROTOTYPE_GETNAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.getNamedItem"),
    NAMEDNODEMAP_PROTOTYPE_SETNAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.setNamedItem"),
    NAMEDNODEMAP_PROTOTYPE_REMOVENAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.removeNamedItem"),
    NAMEDNODEMAP_PROTOTYPE_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.item"),
    NAMEDNODEMAP_PROTOTYPE_GETNAMEDITEMNS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.getNamedItemNS"),
    NAMEDNODEMAP_PROTOTYPE_SETNAMEDITEMNS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.setNamedItemNS"),
    NAMEDNODEMAP_PROTOTYPE_REMOVEDNAMEDITEMNS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.removedNamedItemNS"),
    TEXT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text constructor"),
    TEXT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text.prototype"),
    TEXT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text instances"),
    TEXT_SPLIT_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text.prototype.splitText"),
    TEXT_REPLACE_WHOLE_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text.prototype.replaceWholeText"),
    NOTATION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Notation constructor"),
    NOTATION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Notation.prototype"),
    NOTATION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Notation instances"),

    STRINGLIST_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList constructor"),
    STRINGLIST_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList.prototype"),
    STRINGLIST_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList instances"),
    STRINGLIST_CONTAINS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList.contains"),
    STRINGLIST_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList.item"),

    // /////////////////////////////////////////////////////////////////////////
    // / HTML OBJECTS ///
    // /////////////////////////////////////////////////////////////////////////
    HTMLANCHORELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement constructor"),
    HTMLANCHORELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement.prototype"),
    HTMLANCHORELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement instances"),
    HTMLANCHORELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement.prototype.blur"),
    HTMLANCHORELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement.prototype.focus"),
    HTMLAPPLETELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAppletElement constructor"),
    HTMLAPPLETELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAppletElement.prototype"),
    HTMLAPPLETELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAppletElement instances"),
    HTMLAREAELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAreaElement constructor"),
    HTMLAREAELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAreaElement.prototype"),
    HTMLAREAELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAreaElement instances"),
    HTMLBRELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBRElement constructor"),
    HTMLBRELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBRElement.prototype"),
    HTMLBRELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBRElement instances"),
    HTMLBASEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseElement constructor"),
    HTMLBASEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseElement.prototype"),
    HTMLBASEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseElement instances"),
    HTMLBASEFONTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseFontElement constructor"),
    HTMLBASEFONTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseFontElement.prototype"),
    HTMLBASEFONTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseFontElement instances"),
    HTMLBODYELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBodyElement constructor"),
    HTMLBODYELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBodyElement.prototype"),
    HTMLBODYELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBodyElement instances"),
    HTMLBUTTONELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLButtonElement constructor"),
    HTMLBUTTONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLButtonElement.prototype"),
    HTMLBUTTONELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLButtonElement instances"),
    HTMLCOLLECTION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection constructor"),
    HTMLCOLLECTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection.prototype"),
    HTMLCOLLECTION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection instances"),
    HTMLCOLLECTION_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection.prototype.item"),
    HTMLCOLLECTION_NAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection.prototype.namedItem"),
    HTMLDLISTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDListElement constructor"),
    HTMLDLISTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDListElement.prototype"),
    HTMLDLISTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDListElement instances"),
    HTMLDIRECTORYELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDirectoryElement constructor"),
    HTMLDIRECTORYELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDirectoryElement.prototype"),
    HTMLDIRECTORYELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDirectoryElement instances"),
    HTMLDIVELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDivElement constructor"),
    HTMLDIVELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDivElement.prototype"),
    HTMLDIVELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDivElement instances"),
    HTMLDOCUMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument constructor"),
    HTMLDOCUMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype"),
    HTMLDOCUMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument instances"),
    HTMLDOCUMENT_OPEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.open"),
    HTMLDOCUMENT_CLOSE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.close"),
    HTMLDOCUMENT_WRITE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.write"),
    HTMLDOCUMENT_WRITELN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.writeln"),
    HTMLDOCUMENT_GET_ELEMENTS_BY_NAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.getElementsByName"),
    HTMLDOCUMENT_GET_ELEMENTS_BY_CLASS_NAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.getElementsByClassName"),
    HTMLELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement"),
    HTMLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement.prototype"),
    HTMLELEMENT_GET_ELEMENTS_BY_CLASS_NAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement.prototype.getElementsByClassName"),
    HTMLFIELDSETELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFieldsetElement constructor"),
    HTMLFIELDSETELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFieldsetElement.prototype"),
    HTMLFIELDSETELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFieldsetElement instances"),
    HTMLFONTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFontElement constructor"),
    HTMLFONTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFontElement.prototype"),
    HTMLFONTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFontElement instances"),
    HTMLFORMELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement constructor"),
    HTMLFORMELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement.prototype"),
    HTMLFORMELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement instances"),
    HTMLFORMELEMENT_SUBMIT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement.prototype.submit"),
    HTMLFORMELEMENT_RESET(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement.prototype.reset"),
    HTMLFRAMEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFrameElement constructor"),
    HTMLFRAMEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFrameElement.prototype"),
    HTMLFRAMEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFrameElement instances"),
    HTMLFRAMESETELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFramesetElement constructor"),
    HTMLFRAMESETELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFramesetElement.prototype"),
    HTMLFRAMESETELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFramesetElement instances"),
    HTMLHRELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHRElement constructor"),
    HTMLHRELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHRElement.prototype"),
    HTMLHRELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHRElement instances"),
    HTMLHEADELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadElement constructor"),
    HTMLHEADELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadElement.prototype"),
    HTMLHEADELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadElement instances"),
    HTMLHEADINGELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadingElement constructor"),
    HTMLHEADINGELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadingElement.prototype"),
    HTMLHEADINGELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadingElement instances"),
    HTMLHTMLELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHtmlElement constructor"),
    HTMLHTMLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHtmlElement.prototype"),
    HTMLHTMLELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHtmlElement instances"),
    HTMLIFRAMEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLIFrameElement constructor"),
    HTMLIFRAMEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLIFrameElement.prototype"),
    HTMLIFRAMEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLIFrameElement instances"),
    HTMLIMAGEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLImageElement"),
    HTMLIMAGEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLImageElement.prototype"),
    HTMLINPUTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement constructor"),
    HTMLINPUTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype"),
    HTMLINPUTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement instances"),
    HTMLINPUTELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.blur"),
    HTMLINPUTELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.focus"),
    HTMLINPUTELEMENT_SELECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.select"),
    HTMLINPUTELEMENT_CLICK(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.click"),
    HTMLISINDEXELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLListIndexElement constructor"),
    HTMLISINDEXELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLListIndexElement.prototype"),
    HTMLISINDEXELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLListIndexElement instances"),
    HTMLLIELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLIElement constructor"),
    HTMLLIELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLIElement.prototype"),
    HTMLLIELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLIElement instances"),
    HTMLLABELELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLabelElement constructor"),
    HTMLLABELELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLabelElement.prototype"),
    HTMLLABELELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLabelElement instances"),
    HTMLLEGENDELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLegendElement constructor"),
    HTMLLEGENDELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLegendElement.prototype"),
    HTMLLEGENDELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLegendElement instances"),
    HTMLLINKELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLinkElement constructor"),
    HTMLLINKELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLinkElement.prototype"),
    HTMLLINKELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLinkElement instances"),
    HTMLMAPELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMapElement constructor"),
    HTMLMAPELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMapElement.prototype"),
    HTMLMAPELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMapElement instances"),
    HTMLMENUELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMenuElement constructor"),
    HTMLMENUELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMenuElement.prototype"),
    HTMLMENUELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMenuElement instances"),
    HTMLMETAELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMetaElement constructor"),
    HTMLMETAELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMetaElement.prototype"),
    HTMLMETAELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMetaElement instances"),
    HTMLMODELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLModeElement constructor"),
    HTMLMODELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLModeElement.prototype"),
    HTMLMODELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLModeElement instances"),
    HTMLOLISTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOListElement constructor"),
    HTMLOLISTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOListElement.prototype"),
    HTMLOLISTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOListElement instances"),
    HTMLOBJECTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLObjectElement constructor"),
    HTMLOBJECTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLObjectElement.prototype"),
    HTMLOBJECTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLObjectElement instances"),
    HTMLOPTGROUPELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptGroupElement constructor"),
    HTMLOPTGROUPELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptGroupElement.prototype"),
    HTMLOPTGROUPELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptGroupElement instances"),
    HTMLOPTIONELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionElement constructor"),
    HTMLOPTIONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionElement.prototype"),
    HTMLOPTIONELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionElement instances"),
    HTMLOPTIONSCOLLECTION_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection constructor"),
    HTMLOPTIONSCOLLECTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection.prototype"),
    HTMLOPTIONSCOLLECTION_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection instances"),
    HTMLOPTIONSCOLLECTION_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection.prototype.item"),
    HTMLOPTIONSCOLLECTION_NAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection.prototype.namedItem"),
    HTMLPARAGRAPHELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParagraphElement constructor"),
    HTMLPARAGRAPHELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParagraphElement.prototype"),
    HTMLPARAGRAPHELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParagraphElement instances"),
    HTMLPARAMELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParamElement constructor"),
    HTMLPARAMELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParamElement.prototype"),
    HTMLPARAMELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParamElement instances"),
    HTMLPREELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLPreElement constructor"),
    HTMLPREELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLPreElement.prototype"),
    HTMLPREELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLPreElement instances"),
    HTMLQUOTEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLQuoteElement constructor"),
    HTMLQUOTEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLQuoteElement.prototype"),
    HTMLQUOTEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLQuoteElement instances"),
    HTMLSCRIPTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLScriptElement constructor"),
    HTMLSCRIPTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLScriptElement.prototype"),
    HTMLSCRIPTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLScriptElement instances"),
    HTMLSELECTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement constructor"),
    HTMLSELECTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype"),
    HTMLSELECTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement instances"),
    HTMLSELECTELEMENT_ADD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.add"),
    HTMLSELECTELEMENT_REMOVE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.remove"),
    HTMLSELECTELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.blur"),
    HTMLSELECTELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.focus"),
    HTMLSTYLEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLStyleElement constructor"),
    HTMLSTYLEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLStyleElement.prototype"),
    HTMLSTYLEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLStyleElement instances"),
    HTMLTABLECAPTIONELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCaptionElement constructor"),
    HTMLTABLECAPTIONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCaptionElement.prototype"),
    HTMLTABLECAPTIONELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCaptionElement instances"),
    HTMLTABLECELLELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCellElement constructor"),
    HTMLTABLECELLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCellElement.prototype"),
    HTMLTABLECELLELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCellElement instances"),
    HTMLTABLECOLELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableColElement constructor"),
    HTMLTABLECOLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableColElement.prototype"),
    HTMLTABLECOLELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableColElement instances"),
    HTMLTABLEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement constructor"),
    HTMLTABLEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype"),
    HTMLTABLEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement instances"),
    HTMLTABLEELEMENT_CREATETHEAD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.createTHead"),
    HTMLTABLEELEMENT_DELETETHEAD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteTHead"),
    HTMLTABLEELEMENT_CREATETFOOT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.createTFoot"),
    HTMLTABLEELEMENT_DELETETFOOT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteTFoot"),
    HTMLTABLEELEMENT_CREATECAPTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.createCaption"),
    HTMLTABLEELEMENT_DELETECAPTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteCaption"),
    HTMLTABLEELEMENT_INSERTROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.insertRow"),
    HTMLTABLEELEMENT_DELETEROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteRow"),
    HTMLTABLEROWELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement constructor"),
    HTMLTABLEROWELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement.prototype"),
    HTMLTABLEROWELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement instances"),
    HTMLTABLEROWELEMENT_INSERTCELL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement.prototype.insertCell"),
    HTMLTABLEROWELEMENT_DELETECELL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement.prototype.deleteCell"),
    HTMLTABLESECTIONELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement constructor"),
    HTMLTABLESECTIONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement.prototype"),
    HTMLTABLESECTIONELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement instances"),
    HTMLTABLESECTIONELEMENT_INSERTROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement.prototype.insertRow"),
    HTMLTABLESECTIONELEMENT_DELETEROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement.prototype.deleteRow"),
    HTMLTEXTAREAELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement constructor"),
    HTMLTEXTAREAELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype"),
    HTMLTEXTAREAELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement instances"),
    HTMLTEXTAREAELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype.blur"),
    HTMLTEXTAREAELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype.focus"),
    HTMLTEXTAREAELEMENT_SELECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype.select"),
    HTMLTITLEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTitleElement constructor"),
    HTMLTITLEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTitleElement.prototype"),
    HTMLTITLEELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTitleElement instances"),
    HTMLULISTELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLUListElement constructor"),
    HTMLULISTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLUListElement.prototype"),
    HTMLULISTELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLUListElement instances"),

    // /////////////////////////////////////////////////////////////////////////
    // / NON-STANDARD HTML OBJECTS ///
    // /////////////////////////////////////////////////////////////////////////
    HTMLELEMENT_ATTRIBUTES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement.attributes"), // DOM LEVEL 0
    HTMLIMAGEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLImageElement.constructor"), // DOM LEVEL 0

    // /////////////////////////////////////////////////////////////////////////
    // / CSS ///
    // /////////////////////////////////////////////////////////////////////////
    CSSSTYLEDECLARATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CSSStyleDeclaration"),
    CLIENTBOUNDINGRECT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ClientBoundingRect.constructor"),
    CLIENTBOUNDINGRECT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ClientBoundingRect.prototype"),
    CLIENTBOUNDINGRECT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ClientBoundingRect.instances"),

    // /////////////////////////////////////////////////////////////////////////
    // / HTML5 CANVAS (WHATWG) ///
    // /////////////////////////////////////////////////////////////////////////
    HTMLCANVASELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement"),
    HTMLCANVASELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement.prototype"),
    HTMLCANVASELEMENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement instances"),
    HTMLCANVASELEMENT_TO_DATA_URL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement.prototype.toDataURL"),
    HTMLCANVASELEMENT_GET_CONTEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement.prototype.getContext"),
    CANVASRENDERINGCONTEXT2D(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D"),
    CANVASRENDERINGCONTEXT2D_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype"),

    // State
    CANVASRENDERINGCONTEXT2D_SAVE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.save"),
    CANVASRENDERINGCONTEXT2D_RESTORE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.restore"),

    // Transformations
    CANVASRENDERINGCONTEXT2D_SCALE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.scale"),
    CANVASRENDERINGCONTEXT2D_ROTATE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.rotate"),
    CANVASRENDERINGCONTEXT2D_TRANSLATE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.translate"),
    CANVASRENDERINGCONTEXT2D_TRANSFORM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.transform"),
    CANVASRENDERINGCONTEXT2D_SETTRANSFORM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.setTransform"),

    // Colors & Styles
    CANVASRENDERINGCONTEXT2D_CREATE_LINEAR_GRADIENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createLinearGradient"),
    CANVASRENDERINGCONTEXT2D_CREATE_RADIAL_GRADIENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createRadialGradient"),
    CANVASRENDERINGCONTEXT2D_CREATE_PATTERN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createPattern"),

    // Rects
    CANVASRENDERINGCONTEXT2D_CLEAR_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.clearRect"),
    CANVASRENDERINGCONTEXT2D_FILL_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.fillRect"),
    CANVASRENDERINGCONTEXT2D_STROKE_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.strokeRect"),

    // Paths
    CANVASRENDERINGCONTEXT2D_BEGIN_PATH(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.beginPath"),
    CANVASRENDERINGCONTEXT2D_CLOSE_PATH(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.closePath"),
    CANVASRENDERINGCONTEXT2D_MOVE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.moveTo"),
    CANVASRENDERINGCONTEXT2D_LINE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.lineTo"),
    CANVASRENDERINGCONTEXT2D_QUADRATIC_CURVE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.quadraticCurveTo"),
    CANVASRENDERINGCONTEXT2D_BEZIER_CURVE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.bezierCurveTo"),
    CANVASRENDERINGCONTEXT2D_ARC_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.arcTo"),
    CANVASRENDERINGCONTEXT2D_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.rect"),
    CANVASRENDERINGCONTEXT2D_ARC(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.arc"),
    CANVASRENDERINGCONTEXT2D_FILL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.fill"),
    CANVASRENDERINGCONTEXT2D_STROKE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.stroke"),
    CANVASRENDERINGCONTEXT2D_CLIP(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.clip"),
    CANVASRENDERINGCONTEXT2D_IS_POINT_IN_PATH(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.isPointInPath"),

    // Focus Management
    CANVASRENDERINGCONTEXT2D_DRAW_FOCUS_RING(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.drawFocusRing"),
    CANVASRENDERINGCONTEXT2D_FILL_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.fillText"),
    CANVASRENDERINGCONTEXT2D_STROKE_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.strokeText"),
    CANVASRENDERINGCONTEXT2D_MEASURE_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.measureText"),

    // Drawing Images
    CANVASRENDERINGCONTEXT2D_DRAW_IMAGE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.drawImage"),

    // Pixel Manipulation
    CANVASRENDERINGCONTEXT2D_CREATE_IMAGE_DATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createImageData"),
    CANVASRENDERINGCONTEXT2D_GET_IMAGE_DATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.getImageData"),
    CANVASRENDERINGCONTEXT2D_PUT_IMAGE_DATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.putImageData"),

    CANVASGRADIENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasGradient"),
    CANVASGRADIENT_ADD_COLOR_STOP(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasGradient.addColorStop"),

    CANVASPATTERN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasPattern"),
    CANVASPIXELARRAY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasPixelArray"),
    IMAGEDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ImageData"),
    TEXTMETRICS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "TextMetrics"),

    // /////////////////////////////////////////////////////////////////////////
    // / HTML5 Storage///
    // /////////////////////////////////////////////////////////////////////////
    STORAGE_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Storage constructor"),
    STORAGE_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Storage.prototype"),
    STORAGE_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Storage instances"),
    STORAGE_KEY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Storage.prototype.key"),
    STORAGE_GET_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Storage.prototype.getItem"),
    STORAGE_SET_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Storage.prototype.setItem"),
    STORAGE_REMOVE_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Storage.prototype.removeItem"),
    
    
    // /////////////////////////////////////////////////////////////////////////
    // / AJAX ///
    // /////////////////////////////////////////////////////////////////////////
    READY_STATE_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ReadystateEvent.prototype"),
    READY_STATE_EVENT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ReadystateEvent instances"),
    XML_HTTP_REQUEST_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest"),
    XML_HTTP_REQUEST_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest"),
    XML_HTTP_REQUEST_OPEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest.open"),
    XML_HTTP_REQUEST_SEND(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest.send"),
    XML_HTTP_REQUEST_SET_REQUEST_HEADER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest.setRequestHeader"),
    XML_HTTP_REQUEST_ABORT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest.abort"),
    XML_HTTP_REQUEST_GET_RESPONSE_HEADER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest.getResponseHeader"),
    XML_HTTP_REQUEST_GET_ALL_RESPONSE_HEADERS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest.getAllResponseHeaders"),
    XML_HTTP_REQUEST_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "XmlHttpRequest.prototype"),
    ACTIVE_X_OBJECT_INSTANCES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject"),
    ACTIVE_X_OBJECT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject.prototype"),
    ACTIVE_X_OBJECT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject"),
    ACTIVE_X_OBJECT_OPEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject.open"),
    ACTIVE_X_OBJECT_SEND(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject.send"),
    ACTIVE_X_OBJECT_SET_REQUEST_HEADER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject.setRequestHeader"),
    ACTIVE_X_OBJECT_ABORT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject.abort"),
    ACTIVE_X_OBJECT_GET_RESPONSE_HEADER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject.getResponseHeader"),
    ACTIVE_X_OBJECT_GET_ALL_RESPONSE_HEADERS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ActiveXObject.getAllResponseHeaders"),
    JSON_OBJECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "JSONObject");

    private NativeAPIs api;
    private String string;

    private DOMObjects(NativeAPIs api, String str) {
        this.api = api;
        this.string = str;
    }

    @Override
    public String toString() {
        return string;
    }

    @Override
    public NativeAPIs getAPI() {
        return api;
    }

    @Override
    public boolean hasGetter(String p) {
        return false;
    }

    @Override
    public boolean hasSetter(String p) {
        // TODO: hasSetter, ONLY for HTML elements
        if (this == HTMLIMAGEELEMENT_INSTANCES && DOMEvents.isLoadEventAttribute(p)) {
            // Hack, to support image onload events.
            return true;
        }
        return DOMEvents.isEventAttribute(p)
                || DOMEvents.isAjaxEventProperty(p)
                || p.equalsIgnoreCase("id");
    }

}
