package dk.brics.tajs.analysis.dom;

import dk.brics.tajs.analysis.NativeAPIs;
import dk.brics.tajs.flowgraph.NativeObject;

/**
 * Native DOM objects.
 */
public enum DOMObjects implements NativeObject {

	// /////////////////////////////////////////////////////////////////////////
	// / WINDOW ///
	// /////////////////////////////////////////////////////////////////////////
	// DOM LEVEL 0: WINDOW HISTORY
	WINDOW_HISTORY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history"),
	WINDOW_HISTORY_BACK(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history.back"),
	WINDOW_HISTORY_FORWARD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history.forward"),
	WINDOW_HISTORY_GO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.history.go"),

	// DOM LEVEL 0: WINDOW LOCATION
	WINDOW_LOCATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location"),
	WINDOW_LOCATION_ASSIGN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.assign"),
	WINDOW_LOCATION_RELOAD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.reload"),
	WINDOW_LOCATION_REPLACE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.replace"),
	WINDOW_LOCATION_TOSTRING(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.location.toString"),

	// DOM LEVEL 0: WINDOW NAVIGATOR
	WINDOW_NAVIGATOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Navigator"),

	// DOM LEVEL 0: WINDOW SCREEN
	WINDOW_SCREEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.screen"),

	// DOM LEVEL 0: WINDOW MISC
	WINDOW_ALERT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.alert"),
	WINDOW_ATOB(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.atob"),
	WINDOW_BACK(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.back"),
	WINDOW_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.blur"),
	WINDOW_BTOA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.btoa"),
	WINDOW_CLEAR_INTERVAL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.clearInterval"),
	WINDOW_CLEAR_TIMEOUT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.clearTimeout"),
	WINDOW_CLOSE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.close"),
	WINDOW_CONFIRM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.confirm"),
	WINDOW_ESCAPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.escape"),
	WINDOW_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.focus"),
	WINDOW_FORWARD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.forward"),
	WINDOW_HOME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.home"),
	WINDOW_MAXIMIZE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.maximize"),
	WINDOW_MINIMIZE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.minimize"),
	WINDOW_MOVEBY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.moveBy"),
	WINDOW_MOVETO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.moveTo"),
	WINDOW_OPEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.open"),
	WINDOW_PRINT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.print"),
	WINDOW_PROMPT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.prompt"),
	WINDOW_RESIZEBY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.resizeBy"),
	WINDOW_RESIZETO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.resizeTo"),
	WINDOW_SCROLL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scroll"),
	WINDOW_SCROLLBY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollBy"),
	WINDOW_SCROLLBYLINES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollByLines"),
	WINDOW_SCROLLBYPAGES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollByPages"),
	WINDOW_SCROLLTO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.scrollTo"),
	WINDOW_SET_INTERVAL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.setInterval"),
	WINDOW_SET_TIMEOUT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.setTimeout"),
	WINDOW_STOP(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.stop"),
	WINDOW_UNESCAPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.unescape"),

	// DOM LEVEL 0: addEventListener / removeEventListener
	WINDOW_ADD_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.addEventListener"),
	WINDOW_REMOVE_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Window.removeEventListener"),

	// /////////////////////////////////////////////////////////////////////////
	// / DOCUMENT ///
	// /////////////////////////////////////////////////////////////////////////

	// DOM LEVEL 1
	DOCUMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document"),
	DOCUMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.prototype"),
	DOCUMENT_CREATEPROCESSINGINSTRUCTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createProcessingInstruction"),
	DOCUMENT_CREATE_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createAttribute"),
	DOCUMENT_CREATE_CDATASECTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createCDATASection"),
	DOCUMENT_CREATE_COMMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createComment"),
	DOCUMENT_CREATE_DOCUMENTFRAGMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createDocumentFragment"),
	DOCUMENT_CREATE_ELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createElement"),
	DOCUMENT_CREATE_ENTITYREFERENCE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createEntityReference"),
	DOCUMENT_CREATE_TEXTNODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createTextNode"),
	DOCUMENT_GET_ELEMENTS_BY_TAGNAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.getElementsByTagName"),

	// DOM LEVEL 2
	DOCUMENT_CREATE_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createAttributeNS"),
	DOCUMENT_CREATE_ELEMENT_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.createElementNS"),
	DOCUMENT_GET_ELEMENTS_BY_TAGNAME_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.getElementsByTagNameNS"),
	DOCUMENT_GET_ELEMENT_BY_ID(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.getElementById"),
	DOCUMENT_IMPORT_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.importNode"),

	// DOM LEVEL 3
	DOCUMENT_RENAME_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.renameNode"),
	DOCUMENT_NORMALIZEDOCUMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.normalizeDocument"),
	DOCUMENT_ADOPT_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Document.adoptNode"),

	// /////////////////////////////////////////////////////////////////////////
	// / EVENT ///
	// /////////////////////////////////////////////////////////////////////////

	EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "event"),
	EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "event.prototype"),
	EVENT_STOP_PROPAGATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event.stopPropagation"),
	EVENT_PREVENT_DEFAULT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event.preventDefault"),
	EVENT_INIT_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Event.initEvent"),
	EVENT_TARGET(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget"),
	EVENT_TARGET_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.prototype"),
	EVENT_TARGET_ADD_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.addEventListener"),
	EVENT_TARGET_REMOVE_EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.removeEventListener"),
	EVENT_TARGET_DISPATCH_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventTarget.dispatchEvent"),
	EVENT_LISTENER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventListener"),
	EVENT_LISTENER_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventListener.prototype"),
	EVENT_LISTENER_HANDLE_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventListener.handleEvent"),
	EVENT_EXCEPTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventException"),
	EVENT_EXCEPTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EventException.prototype"),
	DOCUMENT_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentEvent"),
	DOCUMENT_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentEvent.prototype"),
	DOCUMENT_EVENT_CREATE_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentEvent.createEvent"),
	UI_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "UIEvent"),
	UI_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "UIEvent.prototype"),
	UI_EVENT_INIT_UI_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "UIEvent.initUIEvent"),
	MOUSE_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MouseEvent"),
	MOUSE_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MouseEvent.prototype"),
	MOUSE_EVENT_INIT_MOUSE_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MouseEvent.initMouseEvent"),
	KEYBOARD_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent"),
	KEYBOARD_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.prototype"),
	KEYBOARD_EVENT_GET_MODIFIER_STATE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.getModifierState"),
	KEYBOARD_EVENT_INIT_KEYBOARD_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.initKeyboardEvent"),
	KEYBOARD_EVENT_INIT_KEYBOARD_EVENT_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "KeyboardEvent.initKeyboardEventNS"),
	MUTATION_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MutationEvent"),
	MUTATION_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MutationEvent.prototype"),
	MUTATION_EVENT_INIT_MUTATION_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "MutationEvent.initMutationEvent"),
	WHEEL_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent"),
	WHEEL_EVENT_INIT_WHEEL_EVENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent.initWheelEvent"),
	WHEEL_EVENT_INIT_WHEEL_EVENT_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent.initWheelEventNS"),
	WHEEL_EVENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "WheelEvent.prototype"),

	// /////////////////////////////////////////////////////////////////////////
	// / VIEWS ///
	// /////////////////////////////////////////////////////////////////////////
	ABSTRACT_VIEW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "AbstractView"),

	// /////////////////////////////////////////////////////////////////////////
	// / DOM CORE ///
	// /////////////////////////////////////////////////////////////////////////
	ELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element"),
	ELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.prototype"),
	ELEMENT_GET_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttribute"),
	ELEMENT_GET_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttributeNS"),
	ELEMENT_GET_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttributeNode"),
	ELEMENT_GET_ATTRIBUTE_NODE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getAttributeNodeNS"),
	ELEMENT_GET_ELEMENTS_BY_TAGNAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getElementsByTagName"),
	ELEMENT_GET_ELEMENTS_BY_TAGNAME_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.getElementsByTagNameNS"),
	ELEMENT_HAS_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.hasAttribute"),
	ELEMENT_HAS_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.hasAttributeNS"),
	ELEMENT_REMOVE_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.removeAttribute"),
	ELEMENT_REMOVE_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.removeAttributeNS"),
	ELEMENT_REMOVE_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.removeAttributeNode"),
	ELEMENT_SET_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttribute"),
	ELEMENT_SET_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttributeNS"),
	ELEMENT_SET_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttributeNode"),
	ELEMENT_SET_ATTRIBUTE_NODE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setAttributeNodeNS"),
	ELEMENT_SET_ID_ATTRIBUTE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setIdAttributeNode"),
	ELEMENT_SET_ID_ATTRIBUTE_NS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setIdAttributeNodeNS"),
	ELEMENT_SET_ID_ATTRIBUTE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Element.setIdAttributeNodeNode"),

	ATTR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Attr"),
	ATTR_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Attr.prototype"),
	CDATASECTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CDATASection"),
	CDATASECTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CDATASection.prototype"),
	COMMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Comment"),
	COMMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Comment.prototype"),
	CHARACTERDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData"),
	CHARACTERDATA_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.prototype"),
	CHARACTERDATA_SUBSTRINGDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.substringData"),
	CHARACTERDATA_APPENDDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.appendData"),
	CHARACTERDATA_INSERTDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.insertData"),
	CHARACTERDATA_DELETEDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.deleteData"),
	CHARACTERDATA_REPLACEDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CharacterData.replaceData"),
	DOCUMENTTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentType"),
	DOCUMENTTYPE_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentType.prototype"),
	DOCUMENTFRAGMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentFragment"),
	DOCUMENTFRAGMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DocumentFragment.prototype"),
	ENTITY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Entity"),
	ENTITY_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Entity.prototype"),
	ENTITYREFERENCE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EntityReference"),
	ENTITYREFERENCE_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "EntityReference.prototype"),

	NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node"),
	NODE_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.prototype"),
	NODE_APPEND_CHILD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.appendChild"),
	NODE_CLONE_NODE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.cloneNode"),
	NODE_INSERT_BEFORE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.insertBefore"),
	NODE_HAS_CHILD_NODES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.hasChildNodes"),
	NODE_REMOVE_CHILD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.removeChild"),
	NODE_REPLACE_CHILD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.replaceChild"),
	NODE_IS_SUPPORTED(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.isSupported"),
	NODE_HAS_ATTRIBUTES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.hasAttributes"),
	NODE_NORMALIZE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Node.normalize"),

	NODELIST(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NodeList"),
	NODELIST_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NodeList.prototype"),
	NODELIST_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NodeList.item"),

	PROCESSINGINSTRUCTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ProcessingInstruction"),
	PROCESSINGINSTRUCTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ProcessingInstruction.prototype"),
	CONFIGURATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration"),
	CONFIGURATION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.prototype"),
	CONFIGURATION_GET_PARAMETER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.getParameter"),
	CONFIGURATION_SET_PARAMETER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.setParameter"),
	CONFIGURATION_CAN_SET_PARAMETER(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMConfiguration.canSetParameter"),
	DOMEXCEPTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMException"),
	DOMEXCEPTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMException.prototype"),
	DOMIMPLEMENTATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMImplementation"),
	DOMIMPLEMENTATION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "DOMImplementation.prototype"),
	DOMIMPLEMENTATION_HASFEATURE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "hasFeature"),
	DOMIMPLEMENTATION_CREATEDOCUMENTTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "createDocumentType"),
	DOMIMPLEMENTATION_CREATEDOCUMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "createDocument"),
	NAMEDNODEMAP(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap"),
	NAMEDNODEMAP_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.prototype"),
	NAMEDNODEMAP_PROTOTYPE_GETNAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.getNamedItem"),
	NAMEDNODEMAP_PROTOTYPE_SETNAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.setNamedItem"),
	NAMEDNODEMAP_PROTOTYPE_REMOVENAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.removeNamedItem"),
	NAMEDNODEMAP_PROTOTYPE_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.item"),
	NAMEDNODEMAP_PROTOTYPE_GETNAMEDITEMNS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.getNamedItemNS"),
	NAMEDNODEMAP_PROTOTYPE_SETNAMEDITEMNS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.setNamedItemNS"),
	NAMEDNODEMAP_PROTOTYPE_REMOVEDNAMEDITEMNS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "NamedNodeMap.removedNamedItemNS"),
	TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text"),
	TEXT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text.prototype"),
	TEXT_SPLIT_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text.prototype.splitText"),
	TEXT_REPLACE_WHOLE_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Text.prototype.replaceWholeText"),
	NOTATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Notation"),
	NOTATION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "Notation.prototype"),

	STRINGLIST(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList"),
	STRINGLIST_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList.prototype"),
	STRINGLIST_CONTAINS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList.contains"),
	STRINGLIST_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "StringList.item"),

	// /////////////////////////////////////////////////////////////////////////
	// / HTML OBJECTS ///
	// /////////////////////////////////////////////////////////////////////////
	HTMLANCHORELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement"),
	HTMLANCHORELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement.prototype"),
	HTMLANCHORELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement.prototype.blur"),
	HTMLANCHORELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAnchorElement.prototype.focus"),
	HTMLAPPLETELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAppletElement"),
	HTMLAPPLETELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAppletElement.prototype"),
	HTMLAREAELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAreaElement"),
	HTMLAREAELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLAreaElement.prototype"),
	HTMLBRELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBRElement"),
	HTMLBRELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBRElement.prototype"),
	HTMLBASEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseElement"),
	HTMLBASEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseElement.prototype"),
	HTMLBASEFONTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseFontElement"),
	HTMLBASEFONTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBaseFontElement.prototype"),
	HTMLBODYELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBodyElement"),
	HTMLBODYELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLBodyElement.prototype"),
	HTMLBUTTONELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLButtonElement"),
	HTMLBUTTONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLButtonElement.prototype"),
	HTMLCOLLECTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection"),
	HTMLCOLLECTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection.prototype"),
	HTMLCOLLECTION_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection.prototype.item"),
	HTMLCOLLECTION_NAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCollection.prototype.namedItem"),
	HTMLDLISTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDListElement"),
	HTMLDLISTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDListElement.prototype"),
	HTMLDIRECTORYELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDirectoryElement"),
	HTMLDIRECTORYELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDirectoryElement.prototype"),
	HTMLDIVELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDivElement"),
	HTMLDIVELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDivElement.prototype"),
	HTMLDOCUMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument"),
	HTMLDOCUMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype"),
	HTMLDOCUMENT_OPEN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.open"),
	HTMLDOCUMENT_CLOSE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.close"),
	HTMLDOCUMENT_WRITE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.write"),
	HTMLDOCUMENT_WRITELN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.writeln"),
	HTMLDOCUMENT_GET_ELEMENTS_BY_NAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.getElementsByName"),
	HTMLDOCUMENT_GET_ELEMENTS_BY_CLASS_NAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLDocument.prototype.getElementsByClassName"),
	HTMLELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement"),
	HTMLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement.prototype"),
	HTMLELEMENT_GET_ELEMENTS_BY_CLASS_NAME(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement.prototype.getElementsByClassName"),
	HTMLFIELDSETELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFieldsetElement"),
	HTMLFIELDSETELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFieldsetElement.prototype"),
	HTMLFONTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFontElement"),
	HTMLFONTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFontElement.prototype"),
	HTMLFORMELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement"),
	HTMLFORMELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement.prototype"),
	HTMLFORMELEMENT_SUBMIT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement.prototype.submit"),
	HTMLFORMELEMENT_RESET(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFormElement.prototype.reset"),
	HTMLFRAMEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFrameElement"),
	HTMLFRAMEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFrameElement.prototype"),
	HTMLFRAMESETELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFramesetElement"),
	HTMLFRAMESETELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLFramesetElement.prototype"),
	HTMLHRELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHRElement"),
	HTMLHRELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHRElement.prototype"),
	HTMLHEADELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadElement"),
	HTMLHEADELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadElement.prototype"),
	HTMLHEADINGELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadingElement"),
	HTMLHEADINGELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHeadingElement.prototype"),
	HTMLHTMLELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHtmlElement"),
	HTMLHTMLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLHtmlElement.prototype"),
	HTMLIFRAMEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLIFrameElement"),
	HTMLIFRAMEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLIFrameElement.prototype"),
	HTMLIMAGEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLImageElement"),
	HTMLIMAGEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLImageElement.prototype"),
	HTMLINPUTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement"),
	HTMLINPUTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype"),
	HTMLINPUTELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.blur"),
	HTMLINPUTELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.focus"),
	HTMLINPUTELEMENT_SELECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.select"),
	HTMLINPUTELEMENT_CLICK(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLInputElement.prototype.click"),
	HTMLISINDEXELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLListIndexElement"),
	HTMLISINDEXELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLListIndexElement.prototype"),
	HTMLLIELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLIElement"),
	HTMLLIELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLIElement.prototype"),
	HTMLLABELELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLabelElement"),
	HTMLLABELELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLabelElement.prototype"),
	HTMLLEGENDELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLegendElement"),
	HTMLLEGENDELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLegendElement.prototype"),
	HTMLLINKELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLinkElement"),
	HTMLLINKELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLLinkElement.prototype"),
	HTMLMAPELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMapElement"),
	HTMLMAPELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMapElement.prototype"),
	HTMLMENUELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMenuElement"),
	HTMLMENUELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMenuElement.prototype"),
	HTMLMETAELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMetaElement"),
	HTMLMETAELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLMetaElement.prototype"),
	HTMLMODELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLModeElement"),
	HTMLMODELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLModeElement.prototype"),
	HTMLOLISTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOListElement"),
	HTMLOLISTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOListElement.prototype"),
	HTMLOBJECTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLObjectElement"),
	HTMLOBJECTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLObjectElement.prototype"),
	HTMLOPTGROUPELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptGroupElement"),
	HTMLOPTGROUPELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptGroupElement.prototype"),
	HTMLOPTIONELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionElement"),
	HTMLOPTIONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionElement.prototype"),
	HTMLOPTIONSCOLLECTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection"),
	HTMLOPTIONSCOLLECTION_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection.prototype"),
	HTMLOPTIONSCOLLECTION_ITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection.prototype.item"),
	HTMLOPTIONSCOLLECTION_NAMEDITEM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLOptionsCollection.prototype.namedItem"),
	HTMLPARAGRAPHELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParagraphElement"),
	HTMLPARAGRAPHELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParagraphElement.prototype"),
	HTMLPARAMELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParamElement"),
	HTMLPARAMELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLParamElement.prototype"),
	HTMLPREELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLPreElement"),
	HTMLPREELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLPreElement.prototype"),
	HTMLQUOTEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLQuoteElement"),
	HTMLQUOTEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLQuoteElement.prototype"),
	HTMLSCRIPTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLScriptElement"),
	HTMLSCRIPTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLScriptElement.prototype"),
	HTMLSELECTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement"),
	HTMLSELECTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype"),
	HTMLSELECTELEMENT_ADD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.add"),
	HTMLSELECTELEMENT_REMOVE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.remove"),
	HTMLSELECTELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.blur"),
	HTMLSELECTELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLSelectElement.prototype.focus"),
	HTMLSTYLEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLStyleElement"),
	HTMLSTYLEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLStyleElement.prototype"),
	HTMLTABLECAPTIONELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCaptionElement"),
	HTMLTABLECAPTIONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCaptionElement.prototype"),
	HTMLTABLECELLELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCellElement"),
	HTMLTABLECELLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableCellElement.prototype"),
	HTMLTABLECOLELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableColElement"),
	HTMLTABLECOLELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableColElement.prototype"),
	HTMLTABLEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement"),
	HTMLTABLEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype"),
	HTMLTABLEELEMENT_CREATETHEAD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.createTHead"),
	HTMLTABLEELEMENT_DELETETHEAD(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteTHead"),
	HTMLTABLEELEMENT_CREATETFOOT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.createTFoot"),
	HTMLTABLEELEMENT_DELETETFOOT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteTFoot"),
	HTMLTABLEELEMENT_CREATECAPTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.createCaption"),
	HTMLTABLEELEMENT_DELETECAPTION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteCaption"),
	HTMLTABLEELEMENT_INSERTROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.insertRow"),
	HTMLTABLEELEMENT_DELETEROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableElement.prototype.deleteRow"),
	HTMLTABLEROWELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement"),
	HTMLTABLEROWELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement.prototype"),
	HTMLTABLEROWELEMENT_INSERTCELL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement.prototype.insertCell"),
	HTMLTABLEROWELEMENT_DELETECELL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableRowElement.prototype.deleteCell"),
	HTMLTABLESECTIONELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement"),
	HTMLTABLESECTIONELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement.prototype"),
	HTMLTABLESECTIONELEMENT_INSERTROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement.prototype.insertRow"),
	HTMLTABLESECTIONELEMENT_DELETEROW(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTableSectionElement.prototype.deleteRow"),
	HTMLTEXTAREAELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement"),
	HTMLTEXTAREAELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype"),
	HTMLTEXTAREAELEMENT_BLUR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype.blur"),
	HTMLTEXTAREAELEMENT_FOCUS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype.focus"),
	HTMLTEXTAREAELEMENT_SELECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTextAreaElement.prototype.select"),
	HTMLTITLEELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTitleElement"),
	HTMLTITLEELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLTitleElement.prototype"),
	HTMLULISTELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLUListElement"),
	HTMLULISTELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLUListElement.prototype"),

	// /////////////////////////////////////////////////////////////////////////
	// / NON-STANDARD HTML OBJECTS ///
	// /////////////////////////////////////////////////////////////////////////
	HTMLELEMENT_ATTRIBUTES(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLElement.attributes"), // DOM LEVEL 0
	HTMLIMAGEELEMENT_CONSTRUCTOR(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLImageElement.constructor"), // DOM LEVEL 0

	// /////////////////////////////////////////////////////////////////////////
	// / CSS ///
	// /////////////////////////////////////////////////////////////////////////
	CSSSTYLEDECLARATION(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CSSStyleDeclaration"),

	// /////////////////////////////////////////////////////////////////////////
	// / HTML5 CANVAS (WHATWG) ///
	// /////////////////////////////////////////////////////////////////////////
	HTMLCANVASELEMENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement"),
	HTMLCANVASELEMENT_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement.prototype"),
	HTMLCANVASELEMENT_TO_DATA_URL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement.prototype.toDataURL"),
	HTMLCANVASELEMENT_GET_CONTEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "HTMLCanvasElement.prototype.getContext"),
	CANVASRENDERINGCONTEXT2D(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D"),
	CANVASRENDERINGCONTEXT2D_PROTOTYPE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype"),

	// State
	CANVASRENDERINGCONTEXT2D_SAVE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.save"),
	CANVASRENDERINGCONTEXT2D_RESTORE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.restore"),

	// Transformations
	CANVASRENDERINGCONTEXT2D_SCALE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.scale"),
	CANVASRENDERINGCONTEXT2D_ROTATE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.rotate"),
	CANVASRENDERINGCONTEXT2D_TRANSLATE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.translate"),
	CANVASRENDERINGCONTEXT2D_TRANSFORM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.transform"),
	CANVASRENDERINGCONTEXT2D_SETTRANSFORM(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.setTransform"),

	// Colors & Styles
	CANVASRENDERINGCONTEXT2D_CREATE_LINEAR_GRADIENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createLinearGradient"),
	CANVASRENDERINGCONTEXT2D_CREATE_RADIAL_GRADIENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createRadialGradient"),
	CANVASRENDERINGCONTEXT2D_CREATE_PATTERN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createPattern"),

	// Rects
	CANVASRENDERINGCONTEXT2D_CLEAR_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.clearRect"),
	CANVASRENDERINGCONTEXT2D_FILL_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.fillRect"),
	CANVASRENDERINGCONTEXT2D_STROKE_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.strokeRect"),

	// Paths
	CANVASRENDERINGCONTEXT2D_BEGIN_PATH(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.beginPath"),
	CANVASRENDERINGCONTEXT2D_CLOSE_PATH(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.closePath"),
	CANVASRENDERINGCONTEXT2D_MOVE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.moveTo"),
	CANVASRENDERINGCONTEXT2D_LINE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.lineTo"),
	CANVASRENDERINGCONTEXT2D_QUADRATIC_CURVE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.quadraticCurveTo"),
	CANVASRENDERINGCONTEXT2D_BEZIER_CURVE_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.bezierCurveTo"),
	CANVASRENDERINGCONTEXT2D_ARC_TO(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.arcTo"),
	CANVASRENDERINGCONTEXT2D_RECT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.rect"),
	CANVASRENDERINGCONTEXT2D_ARC(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.arc"),
	CANVASRENDERINGCONTEXT2D_FILL(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.fill"),
	CANVASRENDERINGCONTEXT2D_STROKE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.stroke"),
	CANVASRENDERINGCONTEXT2D_CLIP(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.clip"),
	CANVASRENDERINGCONTEXT2D_IS_POINT_IN_PATH(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.isPointInPath"),

	// Focus Management
	CANVASRENDERINGCONTEXT2D_DRAW_FOCUS_RING(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.drawFocusRing"),
	CANVASRENDERINGCONTEXT2D_FILL_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.fillText"),
	CANVASRENDERINGCONTEXT2D_STROKE_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.strokeText"),
	CANVASRENDERINGCONTEXT2D_MEASURE_TEXT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.measureText"),

	// Drawing Images
	CANVASRENDERINGCONTEXT2D_DRAW_IMAGE(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.drawImage"),

	// Pixel Manipulation
	CANVASRENDERINGCONTEXT2D_CREATE_IMAGE_DATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.createImageData"),
	CANVASRENDERINGCONTEXT2D_GET_IMAGE_DATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.getImageData"),
	CANVASRENDERINGCONTEXT2D_PUT_IMAGE_DATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasRenderingContext2D.prototype.putImageData"),

	CANVASGRADIENT(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasGradient"),
	CANVASGRADIENT_ADD_COLOR_STOP(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasGradient.addColorStop"),

	CANVASPATTERN(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasPattern"),
	CANVASPIXELARRAY(NativeAPIs.DOCUMENT_OBJECT_MODEL, "CanvasPixelArray"),
	IMAGEDATA(NativeAPIs.DOCUMENT_OBJECT_MODEL, "ImageData"),
	TEXTMETRICS(NativeAPIs.DOCUMENT_OBJECT_MODEL, "TextMetrics");

	private NativeAPIs api;
	private String string;

	private DOMObjects(NativeAPIs api, String str) {
		this.api = api;
		this.string = str;
	}

	@Override
	public String toString() {
		return string;
	}

	@Override
	public NativeAPIs getAPI() {
		return api;
	}

	@Override
	public boolean hasGetter(String p) {
		return false;
	}

	@Override
	public boolean hasSetter(String p) {
		// TODO: hasSetter, ONLY for HTML elements
		if (this == HTMLIMAGEELEMENT && DOMEvents.isLoadEventAttribute(p)) {
			// Hack, to support image onload events.
			return true;
		}
		return DOMEvents.isEventAttribute(p)
		|| p.equalsIgnoreCase("id");
	}

}
